### ISSUE TITLE
"Failed to parse" errors

### ISSUE THREAD

**Issue by czert** [prometheus/memcached_exporter#42] opened 2018-12-11 10:30 UTC
I'm getting multiple errors on every scrape:

```
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_misses "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
ERRO[0496] Failed to parse touch_hits "": strconv.ParseFloat: parsing "": invalid syntax  source="main.go:479"
```

The scrape itself is successful, but I end up with "NaN" values for all touch metrics. Any idea how resolve this?

**Comment by SuperQ** [comment] 2019-04-14 16:33
Duplicate of https://github.com/prometheus/memcached_exporter/issues/38.

**Closed by SuperQ** 2019-04-14 16:33 UTC
